### ISSUE TITLE
Speech on boarding ships continues

### ISSUE THREAD

**Issue by brpocock** [brpocock/grizzards#556]
When you're boarding the ships, if you hit Fire to dismiss the message before the utterance completes, the PlaySpeech routine will pick up arbitrary contents, from another memory bank perhaps?

**Comment by ZephyrArt** [comment]
supposed fix actually makes next bits of speech impossible --- screws up SpeakJet for future texts

**Comment by brpocock** [comment]
Should be _actually_ fixed in 25f8e5ed355073483fe3a642a7152e61980f61da

@ZephyrArt can you please confirm on hardware and close this if true?
